### ISSUE TITLE
error: dereferencing pointer to incomplete type ‘X509_EXTENSION {aka struct X509_extension_st}’

### ISSUE THREAD

**Issue by dimaw** [macm00v/vmcam#2]
I have error on make in Ubuntu 18.04 (OpenSSL 1.1.0g):
> gcc -DPACKAGE_NAME=\"vmcam\" -DPACKAGE_TARNAME=\"vmcam\" -DPACKAGE_VERSION=\"0.1\" -DPACKAGE_STRING=\"vmcam\ 0.1\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DPACKAGE=\"vmcam\" -DVERSION=\"0.1\" -DHAVE_LIBCRYPTO=1 -DHAVE_LIBSSL=1 -DHAVE_LIBPTHREAD=1 -I.     -g -O2 -MT vm_api.o -MD -MP -MF .deps/vm_api.Tpo -c -o vm_api.o vm_api.c
vm_api.c: In function ‘generate_rsa_pkey’:
vm_api.c:200:2: warning: ‘RSA_generate_key’ is deprecated [-Wdeprecated-declarations]
  rsa_priv_key = RSA_generate_key(kBits, kExp, 0, 0);
  ^~~~~~~~~~~~
In file included from /usr/include/openssl/bn.h:31:0,
                 from /usr/include/openssl/asn1.h:24,
                 from /usr/include/openssl/rsa.h:16,
                 from vm_api.c:30:
/usr/include/openssl/rsa.h:193:1: note: declared here
 DEPRECATEDIN_0_9_8(RSA *RSA_generate_key(int bits, unsigned long e, void
 ^
vm_api.c: In function ‘generate_ski_string’:
vm_api.c:401:37: error: dereferencing pointer to incomplete type ‘X509_EXTENSION {aka struct X509_extension_st}’
   j += sprintf(buf2 + j, "%02X", ext->value->data[i]);
                                     ^~
Makefile:348: recipe for target 'vm_api.o' failed
make[1]: *** [vm_api.o] Error 1

**Comment by macm00v** [comment]
This is a deprecation issue with newer openssl versions. vmcam needs to be built against libssl/openssl 1.0.1e or older, not only because of this issue, but also because most backends use an old DH key which is not supported by newer versions of the library.
