### ISSUE TITLE
Segmentation fault on Debian 10/11

### ISSUE THREAD

**Issue by ijarraki** [macm00v/vmcam#4]
Has anyone been able to run this application on recent Debian? I've successfully compiled it with CFLAGS="-fcommon" against libssl-1.0.1e (and u) and I'm getting a segfault on launch.

vmcam.ini:
CACHE_DIR=[/path/to/cache]
AMINOMAC=[010203040506]
MACHINEID=[010203040506]
PROTOCOL=[1155]
VCASSERVERADDRESS=[127.0.0.1]
VCASSERVERPORT=[12686]
VKSSERVERADDRESS=[127.0.0.1]
VKSSERVERPORT=[12700]
COMPANY=[ACME]
KEY_INTERVAL=[60]
NEWCAMD_PORT=[9950]
CS378X_PORT=[9951]
LISTEN_IP=[127.0.0.1]
USERNAME=[user]
PASSWORD=[pass]
DES_KEY=0102030405060708091011121314

gdb --args ./vmcam -c /path/to/vmcam.ini

[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
VMCam - VCAS SoftCAM for IPTV
[VMCAM] Config file loaded

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7c0676e in __GI___libc_free (mem=<optimized out>) at malloc.c:3124
3124	malloc.c: No such file or directory.
(gdb) bt
#0  0x00007ffff7c0676e in __GI___libc_free (mem=<optimized out>)
    at malloc.c:3124
#1  0x00005555555583ba in main ()
(gdb)

**Comment by ijarraki** [comment]
LD_DEBUG=all:
https://paste.debian.net/hidden/7d04d526/

**Comment by macm00v** [comment]
Looks like you're building against openssl 1.0.1 as stated, but running it with openssl 1.0.0 (from your paste). Not sure if that's the cause though as I'm not an expert at reading traces...

I have vmcam working on Debian stable (11.2), but to avoid any issues with upgrades I run it in a chroot with all the (old) files it needs.

**Comment by ijarraki** [comment]
I am using libssl/openssl 1.0.1e, for some reason 1.0.1 kept using 1.0.0 naming for the .so(s) (just check your own debs from https://jeweet.net/2018/02/26/vmcam-part-ii).

This turned out to be a "bug" in how vmcam loads vmcam.ini outside of the default path (segfaults unless vmcam.ini is found in /etc/ irrespective of -c flag), same goes for several other vars. likely breakage caused by libc changes.

Edit: separate issues.
